spring:
  application:
    name: transaction-data-processor
  datasource:
    url: jdbc:mysql://localhost:3306/batch_transaction_db
    username: root
    password: Password123@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active: prod
